# Generated by Django 6.0.3 on 2026-03-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20)),
                ('item_price', models.FloatField(max_length=10)),
                ('item_desc', models.TextField(max_length=50)),
            ],
        ),
    ]
