# Generated by Django 6.0.3 on 2026-04-11 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_item_item_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['item_name', 'item_price'], name='myapp_item_item_na_8fffba_idx'),
        ),
    ]
